language: node_js
dist: xenial
services:
  - docker
node_js:
  - '10.15.3'
cache:
  yarn: false
branches:
  only:
    - master
    - develop
script:
  # rm package-lock.json if available
  - rm -f package-lock.json
  # download deps yarn
  - yarn
  # build yarn
  - yarn build
  # build & push the dockerfile
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      # login to Dockerhub
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #if [ $TRAVIS_BRANCH = "master" ]; then
      #  LATESTVERSION=latest
      #elif [ $TRAVIS_BRANCH = "develop" ]; then
      #  LATESTVERSION=unstable
      #fi
      LATESTVERSION=latest
      # build & push
      docker build -t semitechnologies/weaviate-playground:$LATESTVERSION .
      docker push semitechnologies/weaviate-playground:$LATESTVERSION
    fi
